"""Aggregator node.

Merges Security Agent + Quality Agent findings, filters out LLM-flagged
likely-false-positives (but still counts them, transparently, so the report
doesn't hide that filtering happened), ranks by severity, and renders a
single markdown report suitable for a PR comment.
"""
from app.agents.state import Finding, ReviewState
from app.core.logging_setup import get_logger

logger = get_logger(__name__)

_SEVERITY_ORDER = {"CRITICAL": 0, "HIGH": 1, "MEDIUM": 2, "LOW": 3, "INFO": 4}
_SEVERITY_EMOJI = {"CRITICAL": "", "HIGH": "", "MEDIUM": "", "LOW": "", "INFO": ""}


def _sort_key(f: Finding):
    return (_SEVERITY_ORDER.get(f["severity"], 5), f["file"], f["line"])


def _render_finding(f: Finding) -> str:
    emoji = _SEVERITY_EMOJI.get(f["severity"], "")
    header = f"{emoji} **{f['severity']}** · `{f['file']}:{f['line']}` · {f['tool']} ({f['rule_id']})"
    body = f["explanation"] or f["message"]
    return f"{header}\n> {body}"


def aggregator_node(state: ReviewState) -> ReviewState:
    security = state.get("security_findings", [])
    quality = state.get("quality_findings", [])

    kept_security = [f for f in security if not f["is_likely_false_positive"]]
    suppressed_count = len(security) - len(kept_security)

    all_findings = sorted(kept_security + quality, key=_sort_key)

    counts_by_severity: dict[str, int] = {}
    for f in all_findings:
        counts_by_severity[f["severity"]] = counts_by_severity.get(f["severity"], 0) + 1

    summary_line = " · ".join(
        f"{_SEVERITY_EMOJI.get(sev, '')} {sev}: {n}"
        for sev, n in sorted(counts_by_severity.items(), key=lambda kv: _SEVERITY_ORDER.get(kv[0], 5))
    ) or "No issues found ✅"

    lines = [
        "##  CodeGuardian AI Review",
        "",
        summary_line,
        "",
    ]

    if suppressed_count:
        lines.append(
            f"_{suppressed_count} static-analysis finding(s) were reviewed and judged likely "
            f"false positives by the triage step, and are omitted below for signal-to-noise. "
            f"This suppression is logged, not silent-in-code._"
        )
        lines.append("")

    if not all_findings:
        lines.append("No security or quality issues detected in this diff. ")
    else:
        for f in all_findings:
            lines.append(_render_finding(f))
            lines.append("")

    errors = state.get("errors", [])
    if errors:
        lines.append("---")
        lines.append("**Note:** some analysis steps had non-fatal errors and may be incomplete:")
        for e in errors:
            lines.append(f"- {e}")

    lines.append("---")
    lines.append("_Generated by CodeGuardian AI — static analysis (Semgrep/Bandit/Gitleaks) "
                 "triaged by Groq/Llama 3.1, quality checks grounded in your team's coding-standards.md._")

    report = "\n".join(lines)
    logger.info("aggregator_complete", finding_count=len(all_findings), suppressed=suppressed_count)
    return {**state, "all_findings": all_findings, "report_markdown": report}
